---

- name: Fix docker to have a provisioned iops drive
  hosts: workers
  user: root
  connection: ssh
#  gather_facts: no

  tasks:

  - name: start docker
    service:
      name: docker
      state: started

  - name: Determine if loopback
    register: loop_device_check
    shell: docker info | grep -i 'Data file:.*loop'
    ignore_errors: yes

  - name: stop docker
    service:
      name: docker
      state: stopped

  - name: scan new disks
    shell: echo "- - -" > /sys/class/scsi_host/host1/scan
    register: disk_label

  - name: delete docker directory /var/lib/docker
    command: rm -rf /var/lib/docker

  - name: create docker pv
    command: parted -s /dev/sdb --script -- mklabel msdos mkpart primary 0% 100% set 1 lvm on

  - name: create docker vg
    lvg:
      vg: dockervg
      pvs: /dev/sdb1

  - name: create thinpoollv in dockervg
    command: lvcreate --wipesignatures y -n thinpoollv dockervg -l 95%VG
    register: extend_output

  - name: create thinpoolmetalv in dockervg
    command: lvcreate --wipesignatures y -n thinpoolmetalv dockervg -l 1%VG
    register: extend_output

  - name: convert the pool to a thin pool
    command: lvconvert -y --zero n -c 512K --thinpool dockervg/thinpoollv --poolmetadata dockervg/thinpoolmetalv
    register: extend_output

  - name: copy docker-thinpool.profile to remote hosts
    copy:
       src: /opt/ansible/playbooks/docker-thinpool.profile
       dest: /etc/lvm/profile/docker-thinpool.profile
       owner: root
       group: root
       mode:  0644
    register: extend_output

  - name: set up lvm profile
    command: lvchange --metadataprofile docker-thinpool dockervg/thinpoollv
    register: extend_output

  - name: copy docker-thinpool.profile to remote hosts
    copy:
       src: /opt/ansible/playbooks/daemon.json
       dest: /etc/docker/daemon.json
       owner: root
       group: root
       mode:  0644
    register: extend_output

  - debug: var=extend_output

  - name: start docker
    service:
      name: docker
      state: restarted

  - name: docker info
    command: docker info
    register: dockerinfo

  - debug: var=dockerinfo

  - name: validate devicemapper
    command: lsblk
    register: extend_output
